### PR TITLE
Now using prop-types, fixing React warning about deprecated React.PropTypes

### PR DESCRIPTION
**Pull request by iPurpl3x**
I fixed the deprecation warning of React by using the new [prop-types](https://github.com/facebook/prop-types) package.
It's the first time I do a pull request, I don't know how this will work with the main repo and if there has to be changes made to package.json version number for a new release etc...

### CODE REVIEW

**Comment by arve0** [comment]
Hi! Thanks for your this. I'll have to look into the testing at saucelabs.

> It's the first time I do a pull request, I don't know how this will work with the main repo and if there has to be changes made to package.json version number for a new release etc...

I'll do a `npm version patch` when the PR is merged and I'm ready to push a new release. Looks good!

**Comment by tscizzle** [comment]
Is this still going to happen? Would be nice to remove that warning (especially if it's done and just needs to be merged)

**Comment by arve0** [comment]
Sorry I never got around merging this. I'm currently on vacation, so will be some time still. You might use @iPurpl3x fork in the meantime. See https://docs.npmjs.com/files/package.json#github-urls

**Comment by arve0** [comment]
Released in v1.0.0.

Had to test locally, can't figure out why saucelabs fails to open the tunnel.

**Pull request merged**
