### PR TITLE
adds onAnimationComplete callback

### PR DESCRIPTION
**Pull request by gregorskii**
adds onAnimationComplete
builds code

for #9

### CODE REVIEW

**Comment by gregorskii** [comment]
Dunno what that build error is. Likely something else... ? :)

**Comment by arve0** [comment]
Thank you for the PR! :octocat: 

Seems like new React requires [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), which is not available in Internet Explorer.

**Comment by arve0** [comment]
Map [has been added earlier](https://github.com/arve0/react-animate-on-change/pull/14/commits/a7bad985105eb7f3ab0f213e1817b10520eddaaf), so unsure why the test fails.

I'm a bit short on time in the weeks that follows, so if you have time to look into it, I would appreciate it.

**Comment by gregorskii** [comment]
Apologies have not had time to look at this, as I have a working fork.

**Comment by arve0** [comment]
Added in #27, but used the name `onAnimationEnd`.

**Pull request closed without merging**
